version: "3.8"
services:
  web:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - ./.next:/app/.next
    environment:
      - NODE_ENV=production
    command: npm run build && npm run start
